window.hug = [
"I don’t want to stop hugging you.",
"Hugging you for hours.",
"Come live in my arms.",
"You’re stuck here with me.",
"One hug isn’t enough.",
"My favorite place is around you.",
"Imagine my arms around you right now.",
"Sending you the tightest hug possible.",
"If you feel warm that’s my hug.",
"Teleporting a hug to you.",
"Close your eyes and fall into me.",
"My arms are your home.",
"I’ll hold you through everything.",
"In my hug you’re safe from the world.",
"You never have to ask for my hugs.",
"I’m always here to hold you.",
"Come here and let me hold you tight.",
"You fit perfectly in my arms.",
"Wrapped around you and never letting go.",
"Right here on my chest where you belong.",
"Holding you like everything is okay.",
"My hug is your safe place.",
"A long warm hug just for you.",
"Rest your head on me.",
"I’m hugging you closer in my thoughts.",
"A forever hug for my baby."
];