window.kiss = [
"A kiss on your forehead.",
"A kiss on your lips.",
"A thousand soft kisses.",
"I’m stealing one right now.",
"Close your eyes…",
"My lips kiss yours.",
"I will kiss your body forever.",
"A slow kiss just for you.",
"Kissing you gently… again and again.",
"One on your cheek.",
"A kiss that lingers.",
"My lips brushing yours.",
"A kiss full of love.",
"Kissing you like I missed you forever.",
"A kiss that says I'm yours.",
"Endless kisses for my baby.",
"A kiss that melts into you.",
"Holding your face and kissing you.",
"A soft kiss before you sleep.",
"A warm kiss just because.",
"A kiss that never wants to end.",
"Come here… kiss.",
"One more kiss… and another.",
"Kissing you slowly.",
"A kiss filled with all my love.",
"A deep gentle kiss.",
"A goodnight kiss from me.",
"A kiss sent through the distance.",
"Mwah.",
"Mwahhh.",
"MWAHHHHHH<3."
];