window.missYou = [
"I’m always right there with you, even if it’s not in person.",
"Counting the minutes until I can hold your hand.",
"You’re living in my heart rent free.",
"Distance is temporary, you’re permanent.",
"It hurts not being next to you.",
"I miss the little things about you.",
"My day feels incomplete without you.",
"You’re my favorite place.",
"I wish I could teleport to you right now.",
"I miss you more than words can say.",
"Every second without you feels longer.",
"I just want to be in your arms.",
"Home is wherever you are.",
"I’m saving all my hugs for you.",
"My heart feels the distance.",
"You’re always on my mind.",
"One day closer to you.",
"I carry you with me everywhere.",
"I miss your voice.",
"I miss your smile.",
"I miss us.",
"I’ll make up for all this distance when I see you."
];