window.overthinking = [
"Shhh… your mind deserves rest.",
"None of those fears are real here.",
"You are enough. Always.",
"I’m not going anywhere.",
"Breathe with me.",
"Your thoughts are loud, but my love is louder.",
"Come here and let your mind be quiet.",
"You don’t have to carry everything alone.",
"I’ve got you, now and always.",
"Let me hold the scary thoughts for you.",
"Everything is okay right here with me.",
"Slow breaths, baby. I’m here.",
"You are safe in my heart.",
"Nothing will take me away from you.",
"Rest your mind on my chest.",
"Those worries don’t stand a chance against us.",
"You don’t have to be perfect for me.",
"I love you even on your hardest days.",
"Your only job right now is to relax.",
"I’m holding you closer in every overthinking moment.",
"Look at me… you’re okay.",
"My arms are your quiet place.",
"Let the thoughts fade, stay with my voice.",
"You’re not alone inside your head.",
"I’ll repeat ‘I love you’ until you believe it.",
"Everything feels softer when you’re with me.",
"Your heart can rest here.",
"I’m not leaving, not now, not ever.",
"You are more than your thoughts.",
"Peace begins with us."
];