window.reasons = [
"Your soft heart.",
"Your laugh.",
"The way you care.",
"You chose me.",
"Your silly moments.",
"Your beautiful voice.",
"Your perfect eyes.",
"The way you make me smile instantly.",
"Your amazing humor.",
"How smart you are.",
"How kind you are.",
"Your cute reactions.",
"Your hot selfies.",
"The way you flirt with me.",
"Your good morning texts.",
"The way you calm me down.",
"How you understand me.",
"You’re my safe place.",
"The way you get clingy.",
"Your adorable jealousy.",
"How you make my heart race.",
"You make my day in a second.",
"Your energy.",
"Your random thoughts.",
"Your late night talks.",
"Your warm presence.",
"The way you love me.",
"You’re the only person I trust.",
"You listen to me.",
"You make everything better.",
"You make me feel special.",
"My heart goes weeeeeeeeeeeeeeeee when I see you.",
"You’re my good girl.",
"You’re my baby.",
"You’re my home.",
"You’re my peace.",
"You're my mommy.",
"The way you say you miss me.",
"How you make me feel wanted.",
"You’re funny without trying.",
"Your little mood swings.",
"Your comforting words.",
"The way you get shy.",
"Your chaos.",
"Your sweetness.",
"Your freaky side.",
"You match my energy.",
"You make normal days special.",
"You make me laugh when I’m down.",
"You’re always on my mind.",
"You’re my dream girl.",
"You’re my favorite notification.",
"The way you care about us.",
"You never give up on me.",
"You make love feel easy.",
"You’re my forever person.",
"You’re the best thing in my life.",
"You make my world brighter.",
"You’re my happiness.",
"You’re my heart.",
"You’re my everything.",
"You’re you."
];