window.sad = [
"Hey… I’m right here with you.",
"Come here, you don’t have to go through this alone.",
"It’s okay to feel like this, I’ve got you.",
"Let me hold you until it passes.",
"You’re safe with me.",
"Breathe slowly… I’m not going anywhere.",
"Your pain is my pain, baby.",
"I wish I could hug you right now.",
"Rest your mind on me.",
"I’m here to make it softer for you.",
"You don’t have to be strong all the time.",
"Cry in my arms, I’m not letting go.",
"I’ll stay with you for as long as you need.",
"Everything feels lighter together.",
"You are not alone in this world.",
"Look at me… I’m right here.",
"My chest is your safe place.",
"Let me protect your heart tonight.",
"I’m holding you closer with every second.",
"We’ll get through this together.",
"You’re the strongest person I know.",
"And even strong girls need hugs.",
"I’m wrapping you in all my love.",
"Nothing will take me away from you.",
"I’m yours especially on the hard days.",
"Close your eyes and fall into my arms.",
"I’m kissing your forehead.",
"Im proud of everything that youre doing my love.",
"I’m calming every storm inside you.",
"Your tears are safe with me.",
"I love you more when you’re like this because I can take care of you."
];